export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';
export const REQUESTS_ROBOTS_PENDING = 'REQUESTS_ROBOTS_PENDING'
export const REQUESTS_ROBOTS_SUCCESSS = 'REQUESTS_ROBOTS_SUCCESSS'
export const REQUESTS_ROBOTS_FAILED = 'REQUESTS_ROBOTS_FAILED'

