export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUESTS_ITEM_PENDING = 'REQUESTS_ITEM_PENDING'
export const REQUESTS_ITEM_SUCCESSS = 'REQUESTS_ITEM_SUCCESSS'
export const REQUESTS_ITEM_FAILED = 'REQUESTS_ITEM_FAILED'
export const GET_ITEM_BY_ID = 'GET_ITEM_BY_ID'

export const REQUESTS_DEPARTMENT_PENDING = 'REQUESTS_DEPARTMENT_PENDING'
export const REQUESTS_DEPARTMENT_SUCCESSS = 'REQUESTS_DEPARTMENT_SUCCESSS'
export const REQUESTS_DEPARTMENT_FAILED = 'REQUESTS_DEPARTMENTS_FAILED'

export const REQUESTS_CATEGORY_PENDING = 'REQUESTS_CATEGORY_PENDING'
export const REQUESTS_CATEGORY_SUCCESSS = 'REQUESTS_CATEGORY_SUCCESSS'
export const REQUESTS_CATEGORY_FAILED = 'REQUESTS_CATEGORY_FAILED'

